### PR TITLE
add eslint config to repo to integrate with text editors

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-syntax-highlight bundle size difference from 3.0.0 to f3bb0200bf29be01cf4d1422db5b2101ff5d1a9b
js: 0.67kb increase (0.27kb/gzip)
An insignificant difference was also found for: css (master), css (internal)

**Comment by origamiserviceuser** [comment]
o-syntax-highlight bundle size difference from 3.0.0 to ed1638a391d5d238d46c39f5c90d38d6a186fcf7
js: 0.67kb increase (0.27kb/gzip)
An insignificant difference was also found for: css (master), css (internal)

**Comment by origamiserviceuser** [comment]
o-syntax-highlight bundle size difference from 3.0.0 to bfa7976b99895561e17c9440fe3aa8bb42fc5bfc
js: 0.67kb increase (0.27kb/gzip)
An insignificant difference was also found for: css (master), css (internal)

**Review by notlee — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
o-syntax-highlight bundle size difference from 3.0.0 to 75c48727a5061b19c833716783d65b19dc5ffc83
js: 0.67kb increase (0.27kb/gzip)
An insignificant difference was also found for: css (master), css (internal)

**Comment by origamiserviceuser** [comment]
o-syntax-highlight bundle size difference from 3.0.0 to 228c01fa79c4437eb136a6731c7c9e94e29224c7
js: 0.67kb increase (0.27kb/gzip)
An insignificant difference was also found for: css (master), css (internal)

**Pull request merged**
